# Generated by Django 2.0.8 on 2018-10-01 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0002_math_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('svg_image', models.FileField(blank=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('add_parallax', models.BooleanField()),
                ('repeat', models.CharField(choices=[('repeat_none', 'No repeat'), ('repeat_x', 'Horizontally'), ('repeat_y', 'Vertically'), ('repeat_both', 'Both directions')], default='repeat_none', max_length=11, verbose_name='background repeat')),
                ('position', models.CharField(choices=[('top left', 'Top left'), ('top center', 'Top center'), ('top right', 'Top right'), ('mid left', 'Mid left'), ('mid center', 'Mid center'), ('mid right', 'Mid right'), ('bottom left', 'Bottom left'), ('bottom center', 'Bottom center'), ('bottom right', 'Bottom right')], default='mid center', max_length=13, verbose_name='background position')),
                ('wagtail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='basepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.HeroImage'),
        ),
    ]
